# Generated by Django 4.2.14 on 2024-08-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
